const MUSIC_DATA = [
  {
    title: "Drum Samples",
    items: [
      {
        id: 1,
        name: "Haze Lofi Drums",
        fileName: "Haze-Lofi-Drums.zip",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 1,
        stripe_price_id: "price_1OlHN5HjhHVwfvlrdNeOBSm1",
        isFeatured: false,
      },
      {
        id: 2,
        name: "Aura Drums",
        fileName: "Aura-Drum-Samples.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 1,
        stripe_price_id: "price_1OlHNYHjhHVwfvlrxRzaB7XH",
        isFeatured: false,
      },
      {
        id: 3,
        name: "Analog Snares",
        fileName: "Analog-Snares.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 0,
        stripe_price_id: "price_1OlHNrHjhHVwfvlrAujJa3vV",
        isFeatured: false,
      },
      {
        id: 4,
        name: "Arist Signature Kicks",
        fileName: "Artist-Signature-Kicks.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 1,
        stripe_price_id: "price_1OlHOKHjhHVwfvlrIPyIwp8Y",
        isFeatured: false,
      },
      {
        id: 5,
        name: "EDM Kicks",
        fileName: "EDM-Kicks.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 0,
        stripe_price_id: "price_1OlHOZHjhHVwfvlrtYk4pq46",
        isFeatured: false,
      },
      {
        id: 6,
        name: "Hip Hop Kicks",
        fileName: "Hip-Hop-Kicks.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 0,
        stripe_price_id: "price_1OlHP1HjhHVwfvlr1jYgDNqz",
        isFeatured: false,
      },
      {
        id: 7,
        name: "Trap Snares",
        fileName: "Trap-Snares.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 0,
        stripe_price_id: "price_1OlHPCHjhHVwfvlrSwPIWLfQ",
        isFeatured: false,
      },
    ],
  },
  {
    title: "Serum Presets",
    items: [
      {
        id: 8,
        name: "Reese Bass Serum",
        fileName: "Reese-Bass-Presets.zip",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 1,
        stripe_price_id: "price_1OlHPfHjhHVwfvlrmGgs7GqH",
        isFeatured: false,
      },
      {
        id: 9,
        name: "Unison Sounds",
        fileName: "Unison-Serum-Presets.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 0,
        stripe_price_id: "price_1OlHQ7HjhHVwfvlrtDknIn3D",
        isFeatured: false,
      },
      {
        id: 10,
        name: "Stranger Things Sounds",
        fileName: "Stranger-Things-Serum-Presets.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 1,
        stripe_price_id: "price_1OlHQPHjhHVwfvlrv8PgGYwY",
        isFeatured: false,
      },
      {
        id: 11,
        name: "808 Sounds",
        fileName: "808-Version-3.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 0,
        stripe_price_id: "price_1OlHQhHjhHVwfvlrlX3WRE9c",
        isFeatured: false,
      },
    ],
  },
  {
    title: "Ambient Tracks",
    items: [
      {
        id: 12,
        name: "Breathe",
        fileName: "Breathe.mp3.zip",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        price: 0,
        stripe_price_id: "price_1OlFIBHjhHVwfvlrLMnvgWVJ",
        isFeatured: false,
      },
      {
        id: 13,
        name: "Ambient Pads",
        fileName: "Ambient Pads.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 1,
        stripe_price_id: "price_1OlFHgHjhHVwfvlrM6Y3LjMZ",
        isFeatured: false,
      },
      {
        id: 14,
        name: "River",
        fileName: "River.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 1,
        stripe_price_id: "price_1OlESPHjhHVwfvlrfzIhjaGO",
        isFeatured: false,
      },
      {
        id: 15,
        name: "Sky",
        fileName: "Sky.zip",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        price: 1,
        stripe_price_id: "price_1OlFtMHjhHVwfvlrW64mY2zQ",
        isFeatured: false,
      },
      {
        id: 16,
        name: "Clouds",
        fileName: "Clouds.zip",
        imageUrl: "/S.jpg",
        price: 1,
        stripe_price_id: "price_1OlFtjHjhHVwfvlrsTeJQXHN",
        isFeatured: false,
      },
    ],
  },
];

export default MUSIC_DATA;
